# -*- coding: utf-8 -*-
"""Sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xex6GneuqVHl7y1yRZCjkgmvB8SBjq6A
"""

!pip install dash pandas plotly

import pandas as pd
import dash
from dash import dcc, html, Input, Output
import plotly.express as px

# Load the dataset
# Make sure 'data.csv' is uploaded to your Colab session
df = pd.read_csv('/content/data.csv')

# Verify the data loaded correctly
df.head()

import plotly.express as px
from dash import dcc, html, Input, Output
import dash

# 1. Initialize the Dash app
external_stylesheets = [
    {
        'href': 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css',
        'rel': 'stylesheet'
    }
]
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

# Professional Dark Theme CSS with high contrast elements
app.index_string = '''
<!DOCTYPE html>
<html>
    <head>
        {%metas%}
        <title>{%title%}</title>
        {%favicon%}
        {%css%}
        <style>
            .themed-dropdown .Select-control {
                background-color: #1e293b !important;
                border: 1px solid #334155 !important;
            }
            .card-style {
                background-color: #1e293b;
                border-radius: 12px;
                padding: 15px;
                margin: 10px;
                border: 1px solid rgba(255, 255, 255, 0.1);
                box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.2);
            }
        </style>
    </head>
    <body>
        {%app_entry%}
        <footer>
            {%config%}
            {%scripts%}
            {%renderer%}
        </footer>
    </body>
</html>
'''

available_products = df['PRODUCT_NAME'].unique().tolist()
dropdown_options = [{'label': '📊 All Products', 'value': 'All'}] + [{'label': f'🔹 {prod}', 'value': prod} for prod in available_products]

# 3. Layout definition
app.layout = html.Div(style={'fontFamily': 'Segoe UI, sans-serif', 'backgroundColor': '#0f172a', 'padding': '20px', 'minHeight': '100vh'}, children=[
    html.Div([
        html.H1("Inventory Intelligence", style={'textAlign': 'left', 'color': 'white', 'margin': '0', 'fontWeight': 'bold'}),
        html.P("High-Visibility Performance Analytics", style={'color': '#38bdf8', 'margin': '5px 0 0 0'})
    ], style={'backgroundColor': '#1e293b', 'padding': '20px', 'borderRadius': '12px', 'marginBottom': '20px', 'borderLeft': '8px solid #38bdf8'}),

    html.Div([
        html.Label("Select Product Filter:", style={'color': '#94a3b8', 'fontWeight': 'bold'}),
        dcc.Dropdown(
            id='product-dropdown', options=dropdown_options, value='All', clearable=False, className='themed-dropdown',
            style={'color': 'black'}
        )
    ], style={'padding': '15px', 'backgroundColor': '#1e293b', 'borderRadius': '12px', 'marginBottom': '20px'}),

    dcc.Loading(type="default", color="#38bdf8", children=[
        html.Div(id='metrics-cards', style={'display': 'flex', 'gap': '15px', 'marginBottom': '15px'}),
        html.Div([
            html.Div([dcc.Graph(id='sales-line-chart')], className='card-style', style={'flex': '1'}),
            html.Div([dcc.Graph(id='inventory-bar-chart')], className='card-style', style={'flex': '1'})
        ], style={'display': 'flex', 'flexWrap': 'wrap'}),
        html.Div([
            html.Div([dcc.Graph(id='market-share-pie')], className='card-style', style={'flex': '1'}),
            html.Div([dcc.Graph(id='stock-stability-scatter')], className='card-style', style={'flex': '1'})
        ], style={'display': 'flex', 'flexWrap': 'wrap'})
    ])
])

@app.callback(
    [Output('sales-line-chart', 'figure'), Output('inventory-bar-chart', 'figure'), Output('market-share-pie', 'figure'),
     Output('stock-stability-scatter', 'figure'), Output('metrics-cards', 'children')],
    [Input('product-dropdown', 'value')]
)
def update_dashboard(selected_product):
    if selected_product == 'All':
        m_df = df.copy()
        display_df = df.groupby('MONTH').agg({'UNIT_SALES': 'sum', 'QUANTITY_ON_HAND': 'mean'}).reset_index()
        supply_val = "Various"
    else:
        m_df = df[df['PRODUCT_NAME'] == selected_product]
        display_df = m_df.sort_values(by='MONTH')
        supply_val = f"{display_df['SUPPLY_TIME'].iloc[0]} Days"

    fig_sales = px.line(display_df, x='MONTH', y='UNIT_SALES', title='Monthly Sales Momentum', template='plotly_dark', markers=True)
    fig_sales.update_traces(line=dict(width=4, color='#00f2fe'))

    fig_inventory = px.bar(display_df, x='MONTH', y='QUANTITY_ON_HAND', title='Stock Levels Over Time', template='plotly_dark', color='QUANTITY_ON_HAND', color_continuous_scale='Viridis')

    fig_pie = px.pie(df.groupby('PRODUCT_NAME')['UNIT_SALES'].sum().reset_index(), values='UNIT_SALES', names='PRODUCT_NAME', template='plotly_dark', color_discrete_sequence=px.colors.qualitative.Plotly, title='Product Portfolio Share')

    fig_stability = px.scatter(df.groupby('PRODUCT_NAME').agg({'UNIT_SALES':'sum','QUANTITY_ON_HAND':'mean'}).reset_index(), x='QUANTITY_ON_HAND', y='UNIT_SALES', color='PRODUCT_NAME', template='plotly_dark', title='Sales vs Inventory Efficiency', color_discrete_sequence=px.colors.qualitative.Bold)

    metrics = [
        html.Div([html.P('Total Unit Sales', style={'color': '#38bdf8'}), html.H3(f"{m_df['UNIT_SALES'].sum():,}", style={'color':'white'})], style={'backgroundColor':'#1e293b','padding':'15px','borderRadius':'10px','flex':'1','textAlign':'center','borderBottom':'4px solid #38bdf8'}),
        html.Div([html.P('Avg Stock Level', style={'color': '#10b981'}), html.H3(f"{m_df['QUANTITY_ON_HAND'].mean():.1f}", style={'color':'white'})], style={'backgroundColor':'#1e293b','padding':'15px','borderRadius':'10px','flex':'1','textAlign':'center','borderBottom':'4px solid #10b981'}),
        html.Div([html.P('Refill Time', style={'color': '#fbbf24'}), html.H3(supply_val, style={'color':'white'})], style={'backgroundColor':'#1e293b','padding':'15px','borderRadius':'10px','flex':'1','textAlign':'center','borderBottom':'4px solid #fbbf24'})
    ]

    return fig_sales, fig_inventory, fig_pie, fig_stability, metrics

# Run the app inline inside the Colab notebook
if __name__ == '__main__':
    from google.colab import output

    # Display the proxy link
    proxy_url = output.eval_js('google.colab.kernel.proxyPort(8050)')
    print(f"Click here to open the dashboard in a new tab: {proxy_url}")

    # Run the server
    # Note: If it's already running, you may need to interrupt the kernel and run again
    app.run(jupyter_mode='inline', port=8050, jupyter_height=650)

import socket

def check_port(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(('127.0.0.1', port)) == 0

port = 8050
if check_port(port):
    print(f"Dash app is successfully running on port {port}.")
    print("You should see the dashboard in the cell output above.")
else:
    print(f"Dash app is NOT detectable on port {port}. Please re-run the previous cell.")